---
title: "Biostat776-Intro-Luoxi Wang"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About me

Hello everyone! My name is Luoxi Wang and I am currently a second-year ScM student in Biochemistry and Molecular Biology. I got my bachelor degrees from University of Strathclyde and China Pharmaceutical University and my major is Biochemistry and Pharmacology. Pandemic happened in the middle of my last year of undergraduate study in Scotland.

My interests focus on cancer researches, especially cancer immunology, tumor microenvironment and immunotherapy. I am actually open to every cancer-related researches and willing to learn all sorts of different techniques. Now I am working on a microbiome and immunotherapy project.

I am a newbie in R🙂️.

## Five fun facts
1. I can play piano and I used to be a keyboard player in our student band.
2. I did scuba diving once in the Great Barrier Reef.
3. I am very interested in outer space.
4. I love movies especially thriller and horror movies.
5. I am more like a dog person but I also like cats.

## Interesting link
[NASA](https://www.nasa.gov/content/goddard/what-did-hubble-see-on-your-birthday) https://www.nasa.gov/content/goddard/what-did-hubble-see-on-your-birthday

This web page is from NASA. They have collected some fascinating pictures taken by Hubble all these years and you can check what interesting cosmic wonder Hubble took on your birthday.

